
{ Pascal Interface }
unit atmcd32d;

interface

const atmcdDLL32='atmcd32d.dll';
const atmcdDLL64='atmcd64d.dll';

//const atmcdDLL = atmcdDLL64;
const atmcdDLL = atmcdDLL32;


const
				DRV_ERROR_CODES = 20001;
				DRV_SUCCESS = 20002;
				DRV_VXDNOTINSTALLED = 20003;
				DRV_ERROR_SCAN = 20004;
				DRV_ERROR_CHECK_SUM = 20005;
				DRV_ERROR_FILELOAD = 20006;
				DRV_UNKNOWN_FUNCTION = 20007;
				DRV_ERROR_VXD_INIT = 20008;
				DRV_ERROR_ADDRESS = 20009;
				DRV_ERROR_PAGELOCK = 20010;
				DRV_ERROR_PAGEUNLOCK = 20011;
				DRV_ERROR_BOARDTEST = 20012;
				DRV_ERROR_ACK = 20013;
				DRV_ERROR_UP_FIFO = 20014;
				DRV_ERROR_PATTERN = 20015;
				DRV_ACQUISITION_ERRORS = 20017;
				DRV_ACQ_BUFFER = 20018;
				DRV_ACQ_DOWNFIFO_FULL = 20019;
				DRV_PROC_UNKONWN_INSTRUCTION = 20020;
				DRV_ILLEGAL_OP_CODE = 20021;
				DRV_KINETIC_TIME_NOT_MET = 20022;
				DRV_ACCUM_TIME_NOT_MET = 20023;
				DRV_NO_NEW_DATA = 20024;
				DRV_PCI_DMA_FAIL =  20025;
				DRV_SPOOLERROR = 20026;
				DRV_SPOOLSETUPERROR = 20027;
				DRV_FILESIZELIMITERROR = 20028;
				DRV_ERROR_FILESAVE = 20029;
				DRV_TEMPERATURE_CODES = 20033;
				DRV_TEMPERATURE_OFF = 20034;
				DRV_TEMPERATURE_NOT_STABILIZED = 20035;
				DRV_TEMPERATURE_STABILIZED = 20036;
				DRV_TEMPERATURE_NOT_REACHED = 20037;
				DRV_TEMPERATURE_OUT_RANGE = 20038;
				DRV_TEMPERATURE_NOT_SUPPORTED = 20039;
				DRV_TEMPERATURE_DRIFT = 20040;
				DRV_TEMP_CODES = 20033;
				DRV_TEMP_OFF = 20034;
				DRV_TEMP_NOT_STABILIZED = 20035;
				DRV_TEMP_STABILIZED = 20036;
				DRV_TEMP_NOT_REACHED = 20037;
				DRV_TEMP_OUT_RANGE = 20038;
				DRV_TEMP_NOT_SUPPORTED = 20039;
				DRV_TEMP_DRIFT = 20040;
				DRV_GENERAL_ERRORS = 20049;
				DRV_INVALID_AUX = 20050;
				DRV_COF_NOTLOADED = 20051;
				DRV_FPGAPROG = 20052;
				DRV_FLEXERROR = 20053;
				DRV_GPIBERROR = 20054;
				DRV_EEPROMVERSIONERROR = 20055;
				DRV_DATATYPE = 20064;
				DRV_DRIVER_ERRORS = 20065;
				DRV_P1INVALID = 20066;
				DRV_P2INVALID = 20067;
				DRV_P3INVALID = 20068;
				DRV_P4INVALID = 20069;
				DRV_INIERROR = 20070;
				DRV_COFERROR = 20071;
				DRV_ACQUIRING = 20072;
				DRV_IDLE = 20073;
				DRV_TEMPCYCLE = 20074;
				DRV_NOT_INITIALIZED = 20075;
				DRV_P5INVALID = 20076;
				DRV_P6INVALID = 20077;
				DRV_INVALID_MODE = 20078;
				DRV_INVALID_FILTER = 20079;
				DRV_I2CERRORS = 20080;
				DRV_I2CDEVNOTFOUND = 20081;
				DRV_I2CTIMEOUT = 20082;
				DRV_P7INVALID = 20083;
				DRV_P8INVALID = 20084;
				DRV_P9INVALID = 20085;
				DRV_P10INVALID = 20086;
				DRV_P11INVALID = 20087;
				DRV_USBERROR = 20089;
				DRV_IOCERROR = 20090;
				DRV_VRMVERSIONERROR = 20091;
				DRV_GATESTEPERROR = 20092;
				DRV_USB_INTERRUPT_ENDPOINT_ERROR = 20093;
				DRV_RANDOM_TRACK_ERROR = 20094;
				DRV_INVALID_TRIGGER_MODE = 20095;
				DRV_LOAD_FIRMWARE_ERROR = 20096;
				DRV_DIVIDE_BY_ZERO_ERROR = 20097;
				DRV_INVALID_RINGEXPOSURES = 20098;
				DRV_BINNING_ERROR = 20099;
				DRV_INVALID_AMPLIFIER = 20100;
				DRV_INVALID_COUNTCONVERT_MODE = 20101;
				DRV_ERROR_NOCAMERA = 20990;
				DRV_NOT_SUPPORTED = 20991;
				DRV_NOT_AVAILABLE = 20992;
				DRV_ERROR_MAP = 20115;
				DRV_ERROR_UNMAP = 20116;
				DRV_ERROR_MDL = 20117;
				DRV_ERROR_UNMDL = 20118;
				DRV_ERROR_BUFFSIZE = 20119;
				DRV_ERROR_NOHANDLE = 20121;
				DRV_GATING_NOT_AVAILABLE = 20130;
				DRV_FPGA_VOLTAGE_ERROR = 20131;
				DRV_OW_CMD_FAIL = 20150;
				DRV_OWMEMORY_BAD_ADDR = 20151;
				DRV_OWCMD_NOT_AVAILABLE = 20152;
				DRV_OW_NO_SLAVES = 20153;
				DRV_OW_NOT_INITIALIZED = 20154;
				DRV_OW_ERROR_SLAVE_NUM = 20155;
				DRV_MSTIMINGS_ERROR = 20156;
				DRV_OA_NULL_ERROR = 20173;
				DRV_OA_PARSE_DTD_ERROR = 20174;
				DRV_OA_DTD_VALIDATE_ERROR = 20175;
				DRV_OA_FILE_ACCESS_ERROR = 20176;
				DRV_OA_FILE_DOES_NOT_EXIST = 20177;
				DRV_OA_XML_INVALID_OR_NOT_FOUND_ERROR = 20178;
				DRV_OA_PRESET_FILE_NOT_LOADED = 20179;
				DRV_OA_USER_FILE_NOT_LOADED = 20180;
				DRV_OA_PRESET_AND_USER_FILE_NOT_LOADED = 20181;
				DRV_OA_INVALID_FILE = 20182;
				DRV_OA_FILE_HAS_BEEN_MODIFIED = 20183;
				DRV_OA_BUFFER_FULL = 20184;
				DRV_OA_INVALID_STRING_LENGTH = 20185;
				DRV_OA_INVALID_CHARS_IN_NAME = 20186;
				DRV_OA_INVALID_NAMING = 20187;
				DRV_OA_GET_CAMERA_ERROR = 20188;
				DRV_OA_MODE_ALREADY_EXISTS = 20189;
				DRV_OA_STRINGS_NOT_EQUAL = 20190;
				DRV_OA_NO_USER_DATA = 20191;
				DRV_OA_VALUE_NOT_SUPPORTED = 20192;
				DRV_OA_MODE_DOES_NOT_EXIST = 20193;
				DRV_OA_CAMERA_NOT_SUPPORTED = 20194;
				DRV_OA_FAILED_TO_GET_MODE = 20195;
				DRV_PROCESSING_FAILED = 20211;
				
		
	  {AT_SDKVersion Definitions}
		AT_SDKVersion = $40000000;
	  {AT_DeviceDriverVersion Definitions}
		AT_DeviceDriverVersion = $40000001;
	  { NOTE: Update the count when you add entries }
    AT_NoOfVersionInfoIds  = 2;
			
		
	  {AT_DDGLite_ChannelA Definitions}
		AT_DDGLite_ChannelA = $40000000;
	  {AT_DDGLite_ChannelB Definitions}
		AT_DDGLite_ChannelB = $40000001;
	  {AT_DDGLite_ChannelC Definitions}
		AT_DDGLite_ChannelC = $40000002;
				
    AT_DDGLite_ControlBit_GlobalEnable   = $01;

    AT_DDGLite_ControlBit_ChannelEnable  = $01;
    AT_DDGLite_ControlBit_FreeRun        = $02;
    AT_DDGLite_ControlBit_DisableOnFrame = $04;
    AT_DDGLite_ControlBit_RestartOnFire  = $08;
    AT_DDGLite_ControlBit_Invert         = $10;
    AT_DDGLite_ControlBit_EnableOnFire   = $20;



 AC_ACQMODE_SINGLE = 1;
 AC_ACQMODE_VIDEO = 2;
 AC_ACQMODE_ACCUMULATE = 4;
 AC_ACQMODE_KINETIC = 8;
 AC_ACQMODE_FRAMETRANSFER = 16;
 AC_ACQMODE_FASTKINETICS = 32;
 AC_ACQMODE_OVERLAP = 64;

 AC_READMODE_FULLIMAGE = 1;
 AC_READMODE_SUBIMAGE = 2;
 AC_READMODE_SINGLETRACK = 4;
 AC_READMODE_FVB = 8;
 AC_READMODE_MULTITRACK = 16;
 AC_READMODE_RANDOMTRACK = 32;
 AC_READMODE_MULTITRACKSCAN = 64;

 AC_TRIGGERMODE_INTERNAL = 1;
 AC_TRIGGERMODE_EXTERNAL = 2;
 AC_TRIGGERMODE_EXTERNAL_FVB_EM = 4;
 AC_TRIGGERMODE_CONTINUOUS = 8;
 AC_TRIGGERMODE_EXTERNALSTART = 16;
 AC_TRIGGERMODE_EXTERNALEXPOSURE = 32;
 AC_TRIGGERMODE_INVERTED = $40;
 AC_TRIGGERMODE_EXTERNAL_CHARGESHIFTING = $80;

// Deprecated for AC_TRIGGERMODE_EXTERNALEXPOSURE
 AC_TRIGGERMODE_BULB = 32;

 AC_CAMERATYPE_PDA = 0;
 AC_CAMERATYPE_IXON = 1;
 AC_CAMERATYPE_ICCD = 2;
 AC_CAMERATYPE_EMCCD = 3;
 AC_CAMERATYPE_CCD = 4;
 AC_CAMERATYPE_ISTAR = 5;
 AC_CAMERATYPE_VIDEO = 6;
 AC_CAMERATYPE_IDUS = 7;
 AC_CAMERATYPE_NEWTON = 8;
 AC_CAMERATYPE_SURCAM = 9;
 AC_CAMERATYPE_USBICCD = 10;
 AC_CAMERATYPE_LUCA = 11;
 AC_CAMERATYPE_RESERVED = 12;
 AC_CAMERATYPE_IKON = 13;
 AC_CAMERATYPE_INGAAS = 14;
 AC_CAMERATYPE_IVAC = 15;
 AC_CAMERATYPE_UNPROGRAMMED = 16;
 AC_CAMERATYPE_CLARA = 17;
 AC_CAMERATYPE_USBISTAR = 18;
 AC_CAMERATYPE_SIMCAM = 19;
 AC_CAMERATYPE_NEO = 20;
 AC_CAMERATYPE_IXONULTRA = 21;
 AC_CAMERATYPE_VOLMOS = 22;

 AC_PIXELMODE_8BIT = 1;
 AC_PIXELMODE_14BIT = 2;
 AC_PIXELMODE_16BIT = 4;
 AC_PIXELMODE_32BIT = 8;

 AC_PIXELMODE_MONO = $000000;
 AC_PIXELMODE_RGB = $010000;
 AC_PIXELMODE_CMY = $020000;

 AC_SETFUNCTION_VREADOUT = $01;
 AC_SETFUNCTION_HREADOUT = $02;
 AC_SETFUNCTION_TEMPERATURE = $04;
 AC_SETFUNCTION_MCPGAIN = $08;
 AC_SETFUNCTION_EMCCDGAIN = $10;
 AC_SETFUNCTION_BASELINECLAMP = $20;
 AC_SETFUNCTION_VSAMPLITUDE = $40;
 AC_SETFUNCTION_HIGHCAPACITY = $80;
 AC_SETFUNCTION_BASELINEOFFSET = $0100;
 AC_SETFUNCTION_PREAMPGAIN = $0200;
 AC_SETFUNCTION_CROPMODE = $0400;
 AC_SETFUNCTION_DMAPARAMETERS = $0800;
 AC_SETFUNCTION_HORIZONTALBIN = $1000;
 AC_SETFUNCTION_MULTITRACKHRANGE = $2000;
 AC_SETFUNCTION_RANDOMTRACKNOGAPS = $4000;
 AC_SETFUNCTION_EMADVANCED = $8000;
 AC_SETFUNCTION_GATEMODE = $010000;
 AC_SETFUNCTION_DDGTIMES = $020000;
 AC_SETFUNCTION_IOC = $040000;
 AC_SETFUNCTION_INTELLIGATE = $080000;
 AC_SETFUNCTION_INSERTION_DELAY = $100000;
 AC_SETFUNCTION_GATESTEP = $200000;
 AC_SETFUNCTION_GATEDELAYSTEP = $200000;
 AC_SETFUNCTION_TRIGGERTERMINATION = $400000;
 AC_SETFUNCTION_EXTENDEDNIR = $800000;
 AC_SETFUNCTION_SPOOLTHREADCOUNT = $1000000;
 AC_SETFUNCTION_REGISTERPACK = $2000000;
 AC_SETFUNCTION_PRESCANS = $4000000;
 AC_SETFUNCTION_GATEWIDTHSTEP = $8000000;
 AC_SETFUNCTION_EXTENDED_CROP_MODE = $10000000;

// Deprecated for AC_SETFUNCTION_MCPGAIN
 AC_SETFUNCTION_GAIN = 8;
 AC_SETFUNCTION_ICCDGAIN = 8;

 AC_GETFUNCTION_TEMPERATURE = $01;
 AC_GETFUNCTION_TARGETTEMPERATURE = $02;
 AC_GETFUNCTION_TEMPERATURERANGE = $04;
 AC_GETFUNCTION_DETECTORSIZE = $08;
 AC_GETFUNCTION_MCPGAIN = $10;
 AC_GETFUNCTION_EMCCDGAIN = $20;
 AC_GETFUNCTION_HVFLAG = $40;
 AC_GETFUNCTION_GATEMODE = $80;
 AC_GETFUNCTION_DDGTIMES = $0100;
 AC_GETFUNCTION_IOC = $0200;
 AC_GETFUNCTION_INTELLIGATE = $0400;
 AC_GETFUNCTION_INSERTION_DELAY = $0800;
 AC_GETFUNCTION_GATESTEP = $1000;
 AC_GETFUNCTION_GATEDELAYSTEP = $1000;
 AC_GETFUNCTION_PHOSPHORSTATUS = $2000;
 AC_GETFUNCTION_MCPGAINTABLE = $4000;
 AC_GETFUNCTION_BASELINECLAMP = $8000;
 AC_GETFUNCTION_GATEWIDTHSTEP = $10000;

// Deprecated for AC_GETFUNCTION_MCPGAIN
 AC_GETFUNCTION_GAIN = $10;
 AC_GETFUNCTION_ICCDGAIN = $10;

 AC_FEATURES_POLLING = 1;
 AC_FEATURES_EVENTS = 2;
 AC_FEATURES_SPOOLING = 4;
 AC_FEATURES_SHUTTER = 8;
 AC_FEATURES_SHUTTEREX = 16;
 AC_FEATURES_EXTERNAL_I2C = 32;
 AC_FEATURES_SATURATIONEVENT = 64;
 AC_FEATURES_FANCONTROL = 128;
 AC_FEATURES_MIDFANCONTROL = 256;
 AC_FEATURES_TEMPERATUREDURINGACQUISITION = 512;
 AC_FEATURES_KEEPCLEANCONTROL = 1024;
 AC_FEATURES_DDGLITE = $0800;
 AC_FEATURES_FTEXTERNALEXPOSURE = $1000;
 AC_FEATURES_KINETICEXTERNALEXPOSURE = $2000;
 AC_FEATURES_DACCONTROL = $4000;
 AC_FEATURES_METADATA = $8000;
 AC_FEATURES_IOCONTROL = $10000;
 AC_FEATURES_PHOTONCOUNTING = $20000;
 AC_FEATURES_COUNTCONVERT = $40000;
 AC_FEATURES_DUALMODE = $80000;
 AC_FEATURES_OPTACQUIRE = $100000;
 AC_FEATURES_REALTIMESPURIOUSNOISEFILTER = $200000;
 AC_FEATURES_POSTPROCESSSPURIOUSNOISEFILTER = $400000;
 AC_FEATURES_DUALPREAMPGAIN = $800000;
 AC_FEATURES_DEFECT_CORRECTION = $1000000;
 AC_FEATURES_STARTOFEXPOSURE_EVENT = $2000000;
 AC_FEATURES_ENDOFEXPOSURE_EVENT = $4000000;
 AC_FEATURES_CAMERALINK = $8000000;

 AC_EMGAIN_8BIT = 1;
 AC_EMGAIN_12BIT = 2;
 AC_EMGAIN_LINEAR12 = 4;
 AC_EMGAIN_REAL12 = 8;



          
	  type
      PAndorCapabilities=^TAndorCapabilities;
      TAndorCapabilities = Record
	     ulSize: Integer;
			ulAcqModes: Integer;
			ulReadModes: Integer;
			ulTriggerModes: Integer;
			ulCameraType: Integer;
			ulPixelMode: Integer;
			ulSetFunctions: Integer;
			ulGetFunctions: Integer;
			ulFeatures: Integer;
			ulPCICard: Integer;
			ulEMGainCapability: Integer;
			ulFTReadModes: Integer;
	  end;

	  type
      TColorDemosaicInfo = Record
	     iX: Integer;
			iY: Integer;
			iAlgorithm: Integer;
			iXPhase: Integer;
			iYPhase: Integer;
			iBackground: Integer;
	  end;

	  type
      TWhiteBalanceInfo = Record
	     iSize: Integer;
			iX: Integer;
			iY: Integer;
			iAlgorithm: Integer;
			iROI_left: Integer;
			iROI_right: Integer;
			iROI_top: Integer;
			iROI_bottom: Integer;
			iOperation: Integer;
	  end;


	  function atmcdAbortAcquisition(): integer; stdcall;
	  function atmcdCancelWait(): integer; stdcall;
	  function atmcdCoolerOFF(): integer; stdcall;
	  function atmcdCoolerON(): integer; stdcall;
	  function atmcdDemosaicImage(grey: PWord; red: PWord; green: PWord; blue: PWord; info: TColorDemosaicInfo): integer; stdcall;
	  function atmcdEnableKeepCleans(iMode: Integer): integer; stdcall;
	  function atmcdFreeInternalMemory(): integer; stdcall;
	  function atmcdGetAcquiredData(arr: PInteger; size: Integer): integer; stdcall;
	  function atmcdGetAcquiredData16(arr: PWord; size: Integer): integer; stdcall;
	  function atmcdGetAcquiredFloatData(arr: PSingle; size: Integer): integer; stdcall;
	  function atmcdGetAcquisitionProgress(var acc: Integer; var series: Integer): integer; stdcall;
	  function atmcdGetAcquisitionTimings(var exposure: Single; var accumulate: Single; var kinetic: Single): integer; stdcall;
	  function atmcdGetAdjustedRingExposureTimes(inumTimes: Integer; var fptimes: Single): integer; stdcall;
	  function atmcdGetAllDMAData(arr: PInteger; size: Integer): integer; stdcall;
	  function atmcdGetAmpDesc(index: Integer; name: PAnsiChar; length: Integer): integer; stdcall;
	  function atmcdGetAmpMaxSpeed(index: Integer; var speed: Single): integer; stdcall;
	  function atmcdGetAvailableCameras(var totalCameras: Integer): integer; stdcall;
	  function atmcdGetBackground(arr: PInteger; size: Integer): integer; stdcall;
	  function atmcdGetBaselineClamp(var state: Integer): integer; stdcall;
	  function atmcdGetBitDepth(channel: Integer; var depth: Integer): integer; stdcall;
	  function atmcdGetCameraEventStatus(var camStatus: Integer): integer; stdcall;
	  function atmcdGetCameraHandle(cameraIndex: Integer; var cameraHandle: Integer): integer; stdcall;
	  function atmcdGetCameraInformation(index: Integer; var information: Integer): integer; stdcall;
	  function atmcdGetCameraSerialNumber(var number: Integer): integer; stdcall;
	  function atmcdGetCapabilities(var caps: TAndorCapabilities): integer; stdcall;
	  function atmcdGetControllerCardModel(controllerCardModel: PAnsiChar): integer; stdcall;
	  function atmcdGetCountConvertWavelengthRange(var minval: Single; var maxval: Single): integer; stdcall;
	  function atmcdGetCurrentCamera(var cameraHandle: Integer): integer; stdcall;
	  function atmcdGetCYMGShift(var iXshift: Integer; var iYShift: Integer): integer; stdcall;
	  function atmcdGetDDGExternalOutputEnabled(uiIndex: Integer; puiEnabled: PInteger): integer; stdcall;
	  function atmcdGetDDGExternalOutputPolarity(uiIndex: Integer; puiPolarity: PInteger): integer; stdcall;
	  function atmcdGetDDGExternalOutputStepEnabled(uiIndex: Integer; puiEnabled: PInteger): integer; stdcall;
	  function atmcdGetDDGExternalOutputTime(uiIndex: Integer; var puiDelay: UInt64; var puiWidth: UInt64): integer; stdcall;
	  function atmcdGetDDGTTLGateWidth(opticalWidth: UInt64; var ttlWidth: UInt64): integer; stdcall;
	  function atmcdGetDDGGateTime(var puiDelay: UInt64; var puiWidth: UInt64): integer; stdcall;
	  function atmcdGetDDGInsertionDelay(piState: PInteger): integer; stdcall;
	  function atmcdGetDDGIntelligate(piState: PInteger): integer; stdcall;
	  function atmcdGetDDGIOC(state: PInteger): integer; stdcall;
	  function atmcdGetDDGIOCFrequency(var frequency: Double): integer; stdcall;
	  function atmcdGetDDGIOCNumber(var numberPulses: Integer): integer; stdcall;
	  function atmcdGetDDGIOCNumberRequested(pulses: PInteger): integer; stdcall;
	  function atmcdGetDDGIOCPeriod(var period: UInt64): integer; stdcall;
	  function atmcdGetDDGIOCPulses(var pulses: Integer): integer; stdcall;
	  function atmcdGetDDGIOCTrigger(trigger: PInteger): integer; stdcall;
	  function atmcdGetDDGOpticalWidthEnabled(puiEnabled: PInteger): integer; stdcall;

	{ DDG Lite functions }												
	  function atmcdGetDDGLiteGlobalControlByte(control: PByte): integer; stdcall;
	  function atmcdGetDDGLiteControlByte(channel: Integer; control: PByte): integer; stdcall;
	  function atmcdGetDDGLiteInitialDelay(channel: Integer; fDelay: PSingle): integer; stdcall;
	  function atmcdGetDDGLitePulseWidth(channel: Integer; fWidth: PSingle): integer; stdcall;
	  function atmcdGetDDGLiteInterPulseDelay(channel: Integer; fDelay: PSingle): integer; stdcall;
	  function atmcdGetDDGLitePulsesPerExposure(channel: Integer; ui32Pulses: PInteger): integer; stdcall;
												
	  function atmcdGetDDGPulse(wid: Double; resolution: Double; var Delay: Double; var Width: Double): integer; stdcall;
	  function atmcdGetDDGStepCoefficients(mode: Integer; p1: Double; p2: Double): integer; stdcall;
	  function atmcdGetDDGWidthStepCoefficients(mode: Integer; p1: Double; p2: Double): integer; stdcall;
	  function atmcdGetDDGStepMode(mode: PInteger): integer; stdcall;
	  function atmcdGetDDGWidthStepMode(mode: PInteger): integer; stdcall;
	  function atmcdGetDetector(var xpixels: Integer; var ypixels: Integer): integer; stdcall;
	  function atmcdGetDICameraInfo(info: Integer): integer; stdcall;
	  function atmcdGetEMAdvanced(var state: Integer): integer; stdcall;
	  function atmcdGetEMCCDGain(var gain: Integer): integer; stdcall;
	  function atmcdGetEMGainRange(var low: Integer; var high: Integer): integer; stdcall;
	  function atmcdGetExternalTriggerTermination(puiTermination: PInteger): integer; stdcall;
	  function atmcdGetFastestRecommendedVSSpeed(var index: Integer; var speed: Single): integer; stdcall;
	  function atmcdGetFIFOUsage(var FIFOusage: Integer): integer; stdcall;
	  function atmcdGetFilterMode(var mode: Integer): integer; stdcall;
	  function atmcdGetFKExposureTime(var time: Single): integer; stdcall;
	  function atmcdGetFKVShiftSpeed(index: Integer; var speed: Integer): integer; stdcall;
	  function atmcdGetFKVShiftSpeedF(index: Integer; var speed: Single): integer; stdcall;
	  function atmcdGetFrontEndStatus(piFlag: PInteger): integer; stdcall;
	  function atmcdGetGateMode(piGatemode: PInteger): integer; stdcall;
	  function atmcdGetHardwareVersion(var PCB: Integer; var Decode: Integer; var dummy1: Integer; var dummy2: Integer; var CameraFirmwareVersion: Integer; var CameraFirmwareBuild: Integer): integer; stdcall;
	  function atmcdGetHeadModel(name: PAnsiChar): integer; stdcall;
	  function atmcdGetHorizontalSpeed(index: Integer; speed: Integer): integer; stdcall;
	  function atmcdGetHSSpeed(channel: Integer; typ: Integer; index: Integer; var speed: Single): integer; stdcall;
	  function atmcdGetHVflag(var bFlag: Integer): integer; stdcall;
	  function atmcdGetID(devNum: Integer; var id: Integer): integer; stdcall;
	  function atmcdGetImageFlip(var iHFlip: Integer; var iVFlip: Integer): integer; stdcall;
	  function atmcdGetImageRotate(var iRotate: Integer): integer; stdcall;
	  function atmcdGetImages(first: Integer; last: Integer; arr: PInteger; size: Integer; var validfirst: Integer; var validlast: Integer): integer; stdcall;
	  function atmcdGetImages16(first: Integer; last: Integer; arr: PWord; size: Integer; var validfirst: Integer; var validlast: Integer): integer; stdcall;
	  function atmcdGetImagesPerDMA(var images: Integer): integer; stdcall;
	  function atmcdGetIRQ(IRQ: PInteger): integer; stdcall;
	  function atmcdGetKeepCleanTime(var KeepCleanTime: Single): integer; stdcall;
	  function atmcdGetMaximumBinning(ReadMode: Integer; HorzVert: Integer; var MaxBinning: Integer): integer; stdcall;
	  function atmcdGetMaximumExposure(var MaxExp: Single): integer; stdcall;
	  function atmcdGetMaximumNumberRingExposureTimes(var number: Integer): integer; stdcall;
	  function atmcdGetMCPGain(piGain: PInteger): integer; stdcall;
	  function atmcdGetMCPGainRange(var iLow: Integer; var iHigh: Integer): integer; stdcall;
	  function atmcdGetMCPGainTable(iNum: Integer; piGain: PInteger; pfPhotoepc: PSingle): integer; stdcall;
	  function atmcdGetMCPVoltage(var iVoltage: Integer): integer; stdcall;
	  function atmcdGetMinimumImageLength(var MinImageLength: Integer): integer; stdcall;
	  function atmcdGetMinimumNumberInSeries(var number: Integer): integer; stdcall;
	  function atmcdGetMostRecentColorImage16(size: Integer; algorithm: Integer; red: PWord; green: PWord; blue: PWord): integer; stdcall;
	  function atmcdGetMostRecentImage(arr: PInteger; size: Integer): integer; stdcall;
	  function atmcdGetMostRecentImage16(arr: PWord; size: Integer): integer; stdcall;
	  function atmcdGetMSTimingsData(TimeOfStart: Single; pfDifferences: PSingle; inoOfImages: Integer): integer; stdcall;
	  function atmcdGetMetaDataInfo(TimeOfStart: Single; pfTimeFromStart: PSingle; index: Integer): integer; stdcall;
	  function atmcdGetMSTimingsEnabled(): integer; stdcall;
	  function atmcdGetRelativeImageTimes(first: Integer; last: Integer; arr: PUInt64; size: Integer): integer; stdcall;
	  function atmcdGetNewData(arr: PInteger; size: Integer): integer; stdcall;
	  function atmcdGetNewData16(arr: PWord; size: Integer): integer; stdcall;
	  function atmcdGetNewData8(arr: PByte; size: Integer): integer; stdcall;
	  function atmcdGetNewFloatData(arr: PSingle; size: Integer): integer; stdcall;
	  function atmcdGetNumberADChannels(var channels: Integer): integer; stdcall;
	  function atmcdGetNumberAmp(var amp: Integer): integer; stdcall;
	  function atmcdGetNumberAvailableImages(var first: Integer; var last: Integer): integer; stdcall;
	  function atmcdGetNumberDDGExternalOutputs(puiCount: PInteger): integer; stdcall;
	  function atmcdGetNumberDevices(var numDevs: Integer): integer; stdcall;
	  function atmcdGetNumberFKVShiftSpeeds(var number: Integer): integer; stdcall;
	  function atmcdGetNumberHorizontalSpeeds(var number: Integer): integer; stdcall;
	  function atmcdGetNumberHSSpeeds(channel: Integer; typ: Integer; var speeds: Integer): integer; stdcall;
	  function atmcdGetNumberNewImages(var first: Integer; var last: Integer): integer; stdcall;
	  function atmcdGetNumberPhotonCountingDivisions(noOfDivisions: Integer): integer; stdcall;
	  function atmcdGetNumberPreAmpGains(var noGains: Integer): integer; stdcall;
	  function atmcdGetNumberRingExposureTimes(var ipnumTimes: Integer): integer; stdcall;
	  function atmcdGetNumberIO(var iNumber: Integer): integer; stdcall;
	  function atmcdGetNumberVerticalSpeeds(var number: Integer): integer; stdcall;
	  function atmcdGetNumberVSAmplitudes(var number: Integer): integer; stdcall;
	  function atmcdGetNumberVSSpeeds(var speeds: Integer): integer; stdcall;
	  function atmcdGetOldestImage(arr: PInteger; size: Integer): integer; stdcall;
	  function atmcdGetOldestImage16(arr: PWord; size: Integer): integer; stdcall;
	  function atmcdGetPhosphorStatus(piFlag: PInteger): integer; stdcall;
	  function atmcdGetPhysicalDMAAddress(Address1: PInteger; Address2: PInteger): integer; stdcall;
	  function atmcdGetPixelSize(var xSize: Single; var ySize: Single): integer; stdcall;
	  function atmcdGetPreAmpGain(index: Integer; var gain: Single): integer; stdcall;
	  function atmcdGetPreAmpGainText(index: Integer; name: PAnsiChar; length: Integer): integer; stdcall;
	  function atmcdGetDualExposureTimes(var exposure1: Single; var exposure2: Single): integer; stdcall;
	  function atmcdGetQE(sensor: PAnsiChar; wavelength: Single; mode: Integer; var QE: Single): integer; stdcall;
	  function atmcdGetReadOutTime(var ReadOutTime: Single): integer; stdcall;
	  function atmcdGetRegisterDump(var mode: Integer): integer; stdcall;
	  function atmcdGetRingExposureRange(var fpMin: Single; var fpMax: Single): integer; stdcall;
	  function atmcdGetSDK3Handle(var Handle: Integer): integer; stdcall;
	  function atmcdGetSensitivity(channel: Integer; horzShift: Integer; amplifier: Integer; pa: Integer; var sensitivity: Single): integer; stdcall;
	  function atmcdGetShutterMinTimes(var minclosingtime: Integer; var minopeningtime: Integer): integer; stdcall;
	  function atmcdGetSizeOfCircularBuffer(var index: Integer): integer; stdcall;
	  function atmcdGetSlotBusDeviceFunction(var dwslot: Integer; var dwBus: Integer; var dwDevice: Integer; var dwFunction: Integer): integer; stdcall;
	  function atmcdGetSoftwareVersion(var eprom: Integer; var coffile: Integer; var vxdrev: Integer; var vxdver: Integer; var dllrev: Integer; var dllver: Integer): integer; stdcall;
	  function atmcdGetSpoolProgress(var index: Integer): integer; stdcall;
	  function atmcdGetStartUpTime(var time: Single): integer; stdcall;
	  function atmcdGetStatus(var status: Integer): integer; stdcall;
	  function atmcdGetTECStatus(piFlag: PInteger): integer; stdcall;
	  function atmcdGetTemperature(var temperature: Integer): integer; stdcall;
	  function atmcdGetTemperatureF(var temperature: Single): integer; stdcall;
	  function atmcdGetTemperatureRange(var mintemp: Integer; var maxtemp: Integer): integer; stdcall;
	  function atmcdGetTemperatureStatus(SensorTemp: PSingle; TargetTemp: PSingle; AmbientTemp: PSingle; CoolerVolts: PSingle): integer; stdcall;
	  function atmcdGetTotalNumberImagesAcquired(var index: Integer): integer; stdcall;
	  function atmcdGetIODirection(index: Integer; var iDirection: Integer): integer; stdcall;
	  function atmcdGetIOLevel(index: Integer; var iLevel: Integer): integer; stdcall;
	  function atmcdGetVersionInfo(arr: Integer; szVersionInfo: PAnsiChar; ui32BufferLen: Integer): integer; stdcall;
	  function atmcdGetVerticalSpeed(index: Integer; var speed: Integer): integer; stdcall;
	  function atmcdGetVirtualDMAAddress(Address1: Integer; Address2: Integer): integer; stdcall;
	  function atmcdGetVSAmplitudeString(index: Integer; text: PAnsiChar): integer; stdcall;
	  function atmcdGetVSAmplitudeFromString(text: PAnsiChar; var index: Integer): integer; stdcall;
	  function atmcdGetVSAmplitudeValue(index: Integer; var value: Integer): integer; stdcall;
	  function atmcdGetVSSpeed(index: Integer; var speed: Single): integer; stdcall;
	  function atmcdGPIBReceive(id: Integer; address: Single; text: PAnsiChar; size: Integer): integer; stdcall;
	  function atmcdGPIBSend(id: Integer; address: Single; text: PAnsiChar): integer; stdcall;
	  function atmcdI2CBurstRead(i2cAddress: Byte; nBytes: Integer; data: PByte): integer; stdcall;
	  function atmcdI2CBurstWrite(i2cAddress: Byte; nBytes: Integer; data: PByte): integer; stdcall;
	  function atmcdI2CRead(deviceID: Byte; intAddress: Byte; var pdata: Byte): integer; stdcall;
	  function atmcdI2CReset(): integer; stdcall;
	  function atmcdI2CWrite(deviceID: Byte; intAddress: Byte; data: Byte): integer; stdcall;
	  function atmcdIdAndorDll(): integer; stdcall;
	  function atmcdInAuxPort(port: Integer; var state: Integer): integer; stdcall;
	  function atmcdInitialize(dir: PAnsiChar): integer; stdcall;
	  function atmcdInitializeDevice(dir: PAnsiChar): integer; stdcall;
	  function atmcdIsAmplifierAvailable(iamp: Integer): integer; stdcall;
	  function atmcdIsCoolerOn(var iCoolerStatus: Integer): integer; stdcall;
	  function atmcdIsCountConvertModeAvailable(mode: Integer): integer; stdcall;
	  function atmcdIsInternalMechanicalShutter(var InternalShutter: Integer): integer; stdcall;
	  function atmcdIsPreAmpGainAvailable(channel: Integer; amplifier: Integer; index: Integer; pa: Integer; var status: Integer): integer; stdcall;
	  function atmcdIsTriggerModeAvailable(iTriggerMode: Integer): integer; stdcall;
	  function atmcdMerge(arr: PInteger; nOrder: Integer; nPoint: Integer; nPixel: Integer; coeff: PSingle; fit: Integer; hbin: Integer; output: PInteger; var start: Single; var step_Renamed: Single): integer; stdcall;
	  function atmcdOutAuxPort(port: Integer; state: Integer): integer; stdcall;
	  function atmcdPrepareAcquisition(): integer; stdcall;
	  function atmcdSaveAsBmp(path: PAnsiChar; palette: PAnsiChar; ymin: Integer; ymax: Integer): integer; stdcall;
	  function atmcdSaveAsCommentedSif(path: PAnsiChar; comment: PAnsiChar): integer; stdcall;
	  function atmcdSaveAsEDF(szPath: PAnsiChar; iMode: Integer): integer; stdcall;
	  function atmcdSaveAsFITS(szFileTitle: PAnsiChar; typ: Integer): integer; stdcall;
	  function atmcdSaveAsRaw(szFileTitle: PAnsiChar; typ: Integer): integer; stdcall;
	  function atmcdSaveAsSif(path: PAnsiChar): integer; stdcall;
	  function atmcdSaveAsSPC(path: PAnsiChar): integer; stdcall;
	  function atmcdSaveAsTiff(path: PAnsiChar; palette: PAnsiChar; position: Integer; typ: Integer): integer; stdcall;
	  function atmcdSaveAsTiffEx(path: PAnsiChar; palette: PAnsiChar; position: Integer; typ: Integer; mode: Integer): integer; stdcall;
	  function atmcdSaveEEPROMToFile(cFileName: PAnsiChar): integer; stdcall;
	  function atmcdSaveToClipBoard(palette: PAnsiChar): integer; stdcall;
	  function atmcdSelectDevice(devNum: Integer): integer; stdcall;
	  function atmcdSendSoftwareTrigger(): integer; stdcall;
	  function atmcdSetAccumulationCycleTime(time: Single): integer; stdcall;
	  function atmcdSetAcqStatusEvent(statusEvent: Integer): integer; stdcall;
	  function atmcdSetAcquisitionMode(mode: Integer): integer; stdcall;
	  function atmcdSetAcquisitionType(typ: Integer): integer; stdcall;
	  function atmcdSetADChannel(channel: Integer): integer; stdcall;
	  function atmcdSetAdvancedTriggerModeState(iState: Integer): integer; stdcall;
	  function atmcdSetBackground(arr: PInteger; size: Integer): integer; stdcall;
	  function atmcdSetBaselineClamp(state: Integer): integer; stdcall;
	  function atmcdSetBaselineOffset(offset: Integer): integer; stdcall;
	  function atmcdSetCameraLinkMode(mode: Integer): integer; stdcall;
	  function atmcdSetCameraStatusEnable(Enable: Integer): integer; stdcall;
	  function atmcdSetChargeShifting(NumberRows: Integer; NumberRepeats: Integer): integer; stdcall;
	  function atmcdSetComplexImage(numAreas: Integer; areas: PInteger): integer; stdcall;
	  function atmcdSetCoolerMode(mode: Integer): integer; stdcall;
	  function atmcdSetCountConvertMode(Mode: Integer): integer; stdcall;
	  function atmcdSetCountConvertWavelength(wavelength: Single): integer; stdcall;
	  function atmcdSetCropMode(active: Integer; cropHeight: Integer; reserved: Integer): integer; stdcall;
	  function atmcdSetCurrentCamera(cameraHandle: Integer): integer; stdcall;
	  function atmcdSetCustomTrackHBin(bin: Integer): integer; stdcall;
	  function atmcdSetDataType(typ: Integer): integer; stdcall;
	  function atmcdSetDACOutput(iOption: Integer; iResolution: Integer; iValue: Integer): integer; stdcall;
	  function atmcdSetDACOutputScale(iScale: Integer): integer; stdcall;
	  function atmcdSetDDGAddress(t0: Byte; t1: Byte; t2: Byte; t3: Byte; address: Byte): integer; stdcall;
	  function atmcdSetDDGExternalOutputEnabled(uiIndex: Integer; uiEnabled: Integer): integer; stdcall;
	  function atmcdSetDDGExternalOutputPolarity(uiIndex: Integer; uiPolarity: Integer): integer; stdcall;
	  function atmcdSetDDGExternalOutputStepEnabled(uiIndex: Integer; uiEnabled: Integer): integer; stdcall;
	  function atmcdSetDDGExternalOutputTime(uiIndex: Integer; uiDelay: UInt64; uiWidth: UInt64): integer; stdcall;
	  function atmcdSetDDGGain(gain: Integer): integer; stdcall;
	  function atmcdSetDDGGateStep(step_Renamed: Double): integer; stdcall;
	  function atmcdSetDDGGateTime(uiDelay: UInt64; uiWidth: UInt64): integer; stdcall;
	  function atmcdSetDDGInsertionDelay(state: Integer): integer; stdcall;
	  function atmcdSetDDGIntelligate(state: Integer): integer; stdcall;
	  function atmcdSetDDGIOC(state: Integer): integer; stdcall;
	  function atmcdSetDDGIOCFrequency(frequency: Double): integer; stdcall;
	  function atmcdSetDDGIOCNumber(numberPulses: Integer): integer; stdcall;
	  function atmcdSetDDGIOCPeriod(period: UInt64): integer; stdcall;
	  function atmcdSetDDGIOCTrigger(trigger: Integer): integer; stdcall;
	  function atmcdSetDDGOpticalWidthEnabled(uiEnabled: Integer): integer; stdcall;

	{ DDG Lite functions }												
	  function atmcdSetDDGLiteGlobalControlByte(control: Byte): integer; stdcall;
	  function atmcdSetDDGLiteControlByte(channel: Integer; control: Byte): integer; stdcall;
	  function atmcdSetDDGLiteInitialDelay(channel: Integer; fDelay: Single): integer; stdcall;
	  function atmcdSetDDGLitePulseWidth(channel: Integer; fWidth: Single): integer; stdcall;
	  function atmcdSetDDGLiteInterPulseDelay(channel: Integer; fDelay: Single): integer; stdcall;
	  function atmcdSetDDGLitePulsesPerExposure(channel: Integer; ui32Pulses: Integer): integer; stdcall;
												
	  function atmcdSetDDGStepCoefficients(mode: Integer; p1: Double; p2: Double): integer; stdcall;
	  function atmcdSetDDGWidthStepCoefficients(mode: Integer; p1: Double; p2: Double): integer; stdcall;
	  function atmcdSetDDGStepMode(mode: Integer): integer; stdcall;
	  function atmcdSetDDGWidthStepMode(mode: Integer): integer; stdcall;
	  function atmcdSetDDGTimes(t0: Double; t1: Double; t2: Double): integer; stdcall;
	  function atmcdSetDDGTriggerMode(mode: Integer): integer; stdcall;
	  function atmcdSetDDGVariableGateStep(mode: Integer; p1: Double; p2: Double): integer; stdcall;
	  function atmcdSetDelayGenerator(board: Integer; address: Single; typ: Integer): integer; stdcall;
	  function atmcdSetDMAParameters(MaxImagesPerDMA: Integer; SecondsPerDMA: Single): integer; stdcall;
	  function atmcdSetDriverEvent(driverEvent: Integer): integer; stdcall;
	  function atmcdSetEMAdvanced(state: Integer): integer; stdcall;
	  function atmcdSetEMCCDGain(gain: Integer): integer; stdcall;
	  function atmcdSetEMClockCompensation(EMClockCompensationFlag: Integer): integer; stdcall;
	  function atmcdSetEMGainMode(mode: Integer): integer; stdcall;
	  function atmcdSetExposureTime(time: Single): integer; stdcall;
	  function atmcdSetExternalTriggerTermination(uiTermination: Integer): integer; stdcall;
	  function atmcdSetFanMode(mode: Integer): integer; stdcall;
	  function atmcdSetFastExtTrigger(mode: Integer): integer; stdcall;
	  function atmcdSetFastKinetics(exposedRows: Integer; seriesLength: Integer; time: Single; mode: Integer; hbin: Integer; vbin: Integer): integer; stdcall;
	  function atmcdSetFastKineticsEx(exposedRows: Integer; seriesLength: Integer; time: Single; mode: Integer; hbin: Integer; vbin: Integer; offset: Integer): integer; stdcall;
	  function atmcdSetFilterMode(mode: Integer): integer; stdcall;
	  function atmcdSetFilterParameters(width: Integer; sensitivity: Single; range: Integer; accept: Single; smooth: Integer; noise: Integer): integer; stdcall;
	  function atmcdSetFKVShiftSpeed(index: Integer): integer; stdcall;
	  function atmcdSetFPDP(state: Integer): integer; stdcall;
	  function atmcdSetFrameTransferMode(mode: Integer): integer; stdcall;
	  function atmcdSetFrontEndEvent(driverEvent: Integer): integer; stdcall;
	  function atmcdSetFullImage(hbin: Integer; vbin: Integer): integer; stdcall;
	  function atmcdSetFVBHBin(bin: Integer): integer; stdcall;
	  function atmcdSetGain(gain: Integer): integer; stdcall;
	  function atmcdSetGate(delay: Single; width: Single; stepRenamed: Single): integer; stdcall;
	  function atmcdSetGateMode(gatemode: Integer): integer; stdcall;
	  function atmcdSetHighCapacity(state: Integer): integer; stdcall;
	  function atmcdSetHorizontalSpeed(index: Integer): integer; stdcall;
	  function atmcdSetHSSpeed(typ: Integer; index: Integer): integer; stdcall;
	  function atmcdSetImage(hbin: Integer; vbin: Integer; hstart: Integer; hend: Integer; vstart: Integer; vend: Integer): integer; stdcall;
	  function atmcdSetImageFlip(iHFlip: Integer; iVFlip: Integer): integer; stdcall;
	  function atmcdSetImageRotate(iRotate: Integer): integer; stdcall;
	  function atmcdSetIsolatedCropMode(active: Integer; cropheight: Integer; cropwidth: Integer; vbin: Integer; hbin: Integer): integer; stdcall;
	  function atmcdSetIsolatedCropModeEx(active: Integer; cropheight: Integer; cropwidth: Integer; vbin: Integer; hbin: Integer; cropleft: Integer; cropbottom: Integer): integer; stdcall;
	  function atmcdSetKineticCycleTime(time: Single): integer; stdcall;
	  function atmcdSetMCPGain(gain: Integer): integer; stdcall;
	  function atmcdSetMCPGating(gating: Integer): integer; stdcall;
	  function atmcdSetMessageWindow(wnd: Integer): integer; stdcall;
	  function atmcdSetMetaData(state: Integer): integer; stdcall;
	  function atmcdSetMultiTrack(number: Integer; height: Integer; offset: Integer; var bottom: Integer; var gap: Integer): integer; stdcall;
	  function atmcdSetMultiTrackHBin(bin: Integer): integer; stdcall;
	  function atmcdSetMultiTrackHRange(iStart: Integer; iEnd: Integer): integer; stdcall;
	  function atmcdSetMultiTrackScan(trackHeight: Integer; numberTracks: Integer; iSIHStart: Integer; iSIHEnd: Integer; trackHBinning: Integer; trackVBinning: Integer; trackGap: Integer; trackOffset: Integer; trackSkip: Integer; numberSubFrames: Integer): integer; stdcall;
	  function atmcdSetNextAddress(data: PInteger; lowAdd: Integer; highAdd: Integer; length: Integer; physical: Integer): integer; stdcall;
	  function atmcdSetNextAddress16(data: PInteger; lowAdd: Integer; highAdd: Integer; length: Integer; physical: Integer): integer; stdcall;
	  function atmcdSetNumberAccumulations(number: Integer): integer; stdcall;
	  function atmcdSetNumberKinetics(number: Integer): integer; stdcall;
	  function atmcdSetNumberPrescans(iNumber: Integer): integer; stdcall;
	  function atmcdSetOutputAmplifier(typ: Integer): integer; stdcall;
	  function atmcdSetOverlapMode(mode: Integer): integer; stdcall;
	  function atmcdSetPCIMode(mode: Integer; value: Integer): integer; stdcall;
	  function atmcdSetPhotonCounting(state: Integer): integer; stdcall;
	  function atmcdSetPhotonCountingThreshold(min: Integer; max: Integer): integer; stdcall;
	  function atmcdSetPhosphorEvent(driverEvent: Integer): integer; stdcall;
	  function atmcdSetPhotonCountingDivisions(noOfDivisions: Integer; divisions: PInteger): integer; stdcall;
	  function atmcdSetPixelMode(bitdepth: Integer; colormode: Integer): integer; stdcall;
	  function atmcdSetPreAmpGain(index: Integer): integer; stdcall;
	  function atmcdSetDualExposureTimes(expTime1: Single; expTime2: Single): integer; stdcall;
	  function atmcdSetDualExposureMode(mode: Integer): integer; stdcall;
	  function atmcdSetRandomTracks(numTracks: Integer; areas: PInteger): integer; stdcall;
	  function atmcdSetReadMode(mode: Integer): integer; stdcall;
	  function atmcdSetReadoutRegisterPacking(mode: Integer): integer; stdcall;
	  function atmcdSetRegisterDump(mode: Integer): integer; stdcall;
	  function atmcdSetRingExposureTimes(numTimes: Integer; times: PSingle): integer; stdcall;
	  function atmcdSetSaturationEvent(saturationEvent: Integer): integer; stdcall;
	  function atmcdSetShutter(typ: Integer; mode: Integer; closingtime: Integer; openingtime: Integer): integer; stdcall;
	  function atmcdSetShutterEx(typ: Integer; mode: Integer; closingtime: Integer; openingtime: Integer; extmode: Integer): integer; stdcall;
	  function atmcdSetShutters(typ: Integer; mode: Integer; closingtime: Integer; openingtime: Integer; exttype: Integer; extmode: Integer; dummy1: Integer; dummy2: Integer): integer; stdcall;
	  function atmcdSetSifComment(comment: PAnsiChar): integer; stdcall;
	  function atmcdSetSingleTrack(centre: Integer; height: Integer): integer; stdcall;
	  function atmcdSetSingleTrackHBin(bin: Integer): integer; stdcall;
	  function atmcdSetSpool(active: Integer; method: Integer; path: PAnsiChar; framebuffersize: Integer): integer; stdcall;
	  function atmcdSetSpoolThreadCount(count: Integer): integer; stdcall;
	  function atmcdSetStorageMode(mode: Integer): integer; stdcall;
	  function atmcdSetTECEvent(driverEvent: Integer): integer; stdcall;
	  function atmcdSetTemperature(temperature: Integer): integer; stdcall;
	  function atmcdSetTemperatureEvent(temperatureEvent: Integer): integer; stdcall;
	  function atmcdSetTriggerMode(mode: Integer): integer; stdcall;
	  function atmcdSetTriggerInvert(mode: Integer): integer; stdcall;
	  function atmcdGetTriggerLevelRange(var minimum: Single; var maximum: Single): integer; stdcall;
	  function atmcdSetTriggerLevel(f_level: Single): integer; stdcall;
	  function atmcdSetIODirection(index: Integer; iDirection: Integer): integer; stdcall;
	  function atmcdSetIOLevel(index: Integer; iLevel: Integer): integer; stdcall;
	  function atmcdSetUserEvent(userEvent: Integer): integer; stdcall;
	  function atmcdSetUSGenomics(width: Integer; height: Integer): integer; stdcall;
	  function atmcdSetVerticalRowBuffer(rows: Integer): integer; stdcall;
	  function atmcdSetVerticalSpeed(index: Integer): integer; stdcall;
	  function atmcdSetVirtualChip(state: Integer): integer; stdcall;
	  function atmcdSetVSAmplitude(index: Integer): integer; stdcall;
	  function atmcdSetVSSpeed(index: Integer): integer; stdcall;
	  function atmcdShutDown(): integer; stdcall;
	  function atmcdStartAcquisition(): integer; stdcall;
	  function atmcdUnMapPhysicalAddress(): integer; stdcall;
	  function atmcdWaitForAcquisition(): integer; stdcall;
	  function atmcdWaitForAcquisitionByHandle(cameraHandle: Integer): integer; stdcall;
	  function atmcdWaitForAcquisitionByHandleTimeOut(cameraHandle: Integer; iTimeOutMs: Integer): integer; stdcall;
	  function atmcdWaitForAcquisitionTimeOut(iTimeOutMs: Integer): integer; stdcall;
	  function atmcdWhiteBalance(wRed: PWord; wGreen: PWord; wBlue: PWord; fRelR: PSingle; fRelB: PSingle; info: TWhiteBalanceInfo): integer; stdcall;
												
	  function atmcdOA_Initialize(pcFilename: PAnsiChar; uiFileNameLen: Integer): integer; stdcall;
	  function atmcdOA_EnableMode(pcModeName: PAnsiChar): integer; stdcall;
	  function atmcdOA_GetModeAcqParams(pcModeName: PAnsiChar; pcListOfParams: PAnsiChar): integer; stdcall;
	  function atmcdOA_GetUserModeNames(pcListOfModes: PAnsiChar): integer; stdcall;
	  function atmcdOA_GetPreSetModeNames(pcListOfModes: PAnsiChar): integer; stdcall;
	  function atmcdOA_GetNumberOfUserModes(puiNumberOfModes: PInteger): integer; stdcall;
	  function atmcdOA_GetNumberOfPreSetModes(puiNumberOfModes: PInteger): integer; stdcall;
	  function atmcdOA_GetNumberOfAcqParams(pcModeName: PAnsiChar; puiNumberOfParams: PInteger): integer; stdcall;
	  function atmcdOA_AddMode(pcModeName: PAnsiChar; uiModeNameLen: Integer; pcModeDescription: PAnsiChar; uiModeDescriptionLen: Integer): integer; stdcall;
	  function atmcdOA_WriteToFile(pcFileName: PAnsiChar; uiFileNameLen: Integer): integer; stdcall;
	  function atmcdOA_DeleteMode(pcModeName: PAnsiChar; uiModeNameLen: Integer): integer; stdcall;
	  function atmcdOA_SetInt(pcModeName: PAnsiChar; pcModeParam: PAnsiChar; iIntValue: Integer): integer; stdcall;
	  function atmcdOA_SetFloat(pcModeName: PAnsiChar; pcModeParam: PAnsiChar; fFloatValue: Single): integer; stdcall;
	  function atmcdOA_SetString(pcModeName: PAnsiChar; pcModeParam: PAnsiChar; pcStringValue: PAnsiChar; uiStringLen: Integer): integer; stdcall;
	  function atmcdOA_GetInt(pcModeName: PAnsiChar; pcModeParam: PAnsiChar; iIntValue: PInteger): integer; stdcall;
	  function atmcdOA_GetFloat(pcModeName: PAnsiChar; pcModeParam: PAnsiChar; fFloatValue: PSingle): integer; stdcall;
	  function atmcdOA_GetString(pcModeName: PAnsiChar; pcModeParam: PAnsiChar; pcStringValue: PAnsiChar; uiStringLen: Integer): integer; stdcall;
												
	  function atmcdFilter_SetMode(mode: Integer): integer; stdcall;
	  function atmcdFilter_GetMode(mode: PInteger): integer; stdcall;
	  function atmcdFilter_SetThreshold(threshold: Single): integer; stdcall;
	  function atmcdFilter_GetThreshold(threshold: PSingle): integer; stdcall;
	  function atmcdFilter_SetDataAveragingMode(mode: Integer): integer; stdcall;
	  function atmcdFilter_GetDataAveragingMode(mode: PInteger): integer; stdcall;
	  function atmcdFilter_SetAveragingFrameCount(frames: Integer): integer; stdcall;
	  function atmcdFilter_GetAveragingFrameCount(frames: PInteger): integer; stdcall;
	  function atmcdFilter_SetAveragingFactor(averagingFactor: Integer): integer; stdcall;
	  function atmcdFilter_GetAveragingFactor(averagingFactor: PInteger): integer; stdcall;
												
	  function atmcdPostProcessNoiseFilter(pInputImage: PInteger; pOutputImage: PInteger; iOutputBufferSize: Integer; iBaseline: Integer; iMode: Integer; fThreshold: Single; iHeight: Integer; iWidth: Integer): integer; stdcall;
	  function atmcdPostProcessCountConvert(pInputImage: PInteger; pOutputImage: PInteger; iOutputBufferSize: Integer; iNumImages: Integer; iBaseline: Integer; iMode: Integer; iEmGain: Integer; fQE: Single; fSensitivity: Single; iHeight: Integer; iWidth: Integer): integer; stdcall;
	  function atmcdPostProcessPhotonCounting(pInputImage: PInteger; pOutputImage: PInteger; iOutputBufferSize: Integer; iNumImages: Integer; iNumframes: Integer; iNumberOfThresholds: Integer; pfThreshold: PSingle; iHeight: Integer; iWidth: Integer): integer; stdcall;
	  function atmcdPostProcessDataAveraging(pInputImage: PInteger; pOutputImage: PInteger; iOutputBufferSize: Integer; iNumImages: Integer; iAveragingFilterMode: Integer; iHeight: Integer; iWidth: Integer; iFrameCount: Integer; iAveragingFactor: Integer): integer; stdcall;

   
implementation
		
	  function atmcdAbortAcquisition; external atmcdDLL name 'AbortAcquisition';
	  function atmcdCancelWait; external atmcdDLL name 'CancelWait';
	  function atmcdCoolerOFF; external atmcdDLL name 'CoolerOFF';
	  function atmcdCoolerON; external atmcdDLL name 'CoolerON';
	  function atmcdDemosaicImage; external atmcdDLL name 'DemosaicImage';
	  function atmcdEnableKeepCleans; external atmcdDLL name 'EnableKeepCleans';
	  function atmcdFreeInternalMemory; external atmcdDLL name 'FreeInternalMemory';
	  function atmcdGetAcquiredData; external atmcdDLL name 'GetAcquiredData';
	  function atmcdGetAcquiredData16; external atmcdDLL name 'GetAcquiredData16';
	  function atmcdGetAcquiredFloatData; external atmcdDLL name 'GetAcquiredFloatData';
	  function atmcdGetAcquisitionProgress; external atmcdDLL name 'GetAcquisitionProgress';
	  function atmcdGetAcquisitionTimings; external atmcdDLL name 'GetAcquisitionTimings';
	  function atmcdGetAdjustedRingExposureTimes; external atmcdDLL name 'GetAdjustedRingExposureTimes';
	  function atmcdGetAllDMAData; external atmcdDLL name 'GetAllDMAData';
	  function atmcdGetAmpDesc; external atmcdDLL name 'GetAmpDesc';
	  function atmcdGetAmpMaxSpeed; external atmcdDLL name 'GetAmpMaxSpeed';
	  function atmcdGetAvailableCameras; external atmcdDLL name 'GetAvailableCameras';
	  function atmcdGetBackground; external atmcdDLL name 'GetBackground';
	  function atmcdGetBaselineClamp; external atmcdDLL name 'GetBaselineClamp';
	  function atmcdGetBitDepth; external atmcdDLL name 'GetBitDepth';
	  function atmcdGetCameraEventStatus; external atmcdDLL name 'GetCameraEventStatus';
	  function atmcdGetCameraHandle; external atmcdDLL name 'GetCameraHandle';
	  function atmcdGetCameraInformation; external atmcdDLL name 'GetCameraInformation';
	  function atmcdGetCameraSerialNumber; external atmcdDLL name 'GetCameraSerialNumber';
	  function atmcdGetCapabilities; external atmcdDLL name 'GetCapabilities';
	  function atmcdGetControllerCardModel; external atmcdDLL name 'GetControllerCardModel';
	  function atmcdGetCountConvertWavelengthRange; external atmcdDLL name 'GetCountConvertWavelengthRange';
	  function atmcdGetCurrentCamera; external atmcdDLL name 'GetCurrentCamera';
	  function atmcdGetCYMGShift; external atmcdDLL name 'GetCYMGShift';
	  function atmcdGetDDGExternalOutputEnabled; external atmcdDLL name 'GetDDGExternalOutputEnabled';
	  function atmcdGetDDGExternalOutputPolarity; external atmcdDLL name 'GetDDGExternalOutputPolarity';
	  function atmcdGetDDGExternalOutputStepEnabled; external atmcdDLL name 'GetDDGExternalOutputStepEnabled';
	  function atmcdGetDDGExternalOutputTime; external atmcdDLL name 'GetDDGExternalOutputTime';
	  function atmcdGetDDGTTLGateWidth; external atmcdDLL name 'GetDDGTTLGateWidth';
	  function atmcdGetDDGGateTime; external atmcdDLL name 'GetDDGGateTime';
	  function atmcdGetDDGInsertionDelay; external atmcdDLL name 'GetDDGInsertionDelay';
	  function atmcdGetDDGIntelligate; external atmcdDLL name 'GetDDGIntelligate';
	  function atmcdGetDDGIOC; external atmcdDLL name 'GetDDGIOC';
	  function atmcdGetDDGIOCFrequency; external atmcdDLL name 'GetDDGIOCFrequency';
	  function atmcdGetDDGIOCNumber; external atmcdDLL name 'GetDDGIOCNumber';
	  function atmcdGetDDGIOCNumberRequested; external atmcdDLL name 'GetDDGIOCNumberRequested';
	  function atmcdGetDDGIOCPeriod; external atmcdDLL name 'GetDDGIOCPeriod';
	  function atmcdGetDDGIOCPulses; external atmcdDLL name 'GetDDGIOCPulses';
	  function atmcdGetDDGIOCTrigger; external atmcdDLL name 'GetDDGIOCTrigger';
	  function atmcdGetDDGOpticalWidthEnabled; external atmcdDLL name 'GetDDGOpticalWidthEnabled';
	  function atmcdGetDDGLiteGlobalControlByte; external atmcdDLL name 'GetDDGLiteGlobalControlByte';
	  function atmcdGetDDGLiteControlByte; external atmcdDLL name 'GetDDGLiteControlByte';
	  function atmcdGetDDGLiteInitialDelay; external atmcdDLL name 'GetDDGLiteInitialDelay';
	  function atmcdGetDDGLitePulseWidth; external atmcdDLL name 'GetDDGLitePulseWidth';
	  function atmcdGetDDGLiteInterPulseDelay; external atmcdDLL name 'GetDDGLiteInterPulseDelay';
	  function atmcdGetDDGLitePulsesPerExposure; external atmcdDLL name 'GetDDGLitePulsesPerExposure';
	  function atmcdGetDDGPulse; external atmcdDLL name 'GetDDGPulse';
	  function atmcdGetDDGStepCoefficients; external atmcdDLL name 'GetDDGStepCoefficients';
	  function atmcdGetDDGWidthStepCoefficients; external atmcdDLL name 'GetDDGWidthStepCoefficients';
	  function atmcdGetDDGStepMode; external atmcdDLL name 'GetDDGStepMode';
	  function atmcdGetDDGWidthStepMode; external atmcdDLL name 'GetDDGWidthStepMode';
	  function atmcdGetDetector; external atmcdDLL name 'GetDetector';
	  function atmcdGetDICameraInfo; external atmcdDLL name 'GetDICameraInfo';
	  function atmcdGetEMAdvanced; external atmcdDLL name 'GetEMAdvanced';
	  function atmcdGetEMCCDGain; external atmcdDLL name 'GetEMCCDGain';
	  function atmcdGetEMGainRange; external atmcdDLL name 'GetEMGainRange';
	  function atmcdGetExternalTriggerTermination; external atmcdDLL name 'GetExternalTriggerTermination';
	  function atmcdGetFastestRecommendedVSSpeed; external atmcdDLL name 'GetFastestRecommendedVSSpeed';
	  function atmcdGetFIFOUsage; external atmcdDLL name 'GetFIFOUsage';
	  function atmcdGetFilterMode; external atmcdDLL name 'GetFilterMode';
	  function atmcdGetFKExposureTime; external atmcdDLL name 'GetFKExposureTime';
	  function atmcdGetFKVShiftSpeed; external atmcdDLL name 'GetFKVShiftSpeed';
	  function atmcdGetFKVShiftSpeedF; external atmcdDLL name 'GetFKVShiftSpeedF';
	  function atmcdGetFrontEndStatus; external atmcdDLL name 'GetFrontEndStatus';
	  function atmcdGetGateMode; external atmcdDLL name 'GetGateMode';
	  function atmcdGetHardwareVersion; external atmcdDLL name 'GetHardwareVersion';
	  function atmcdGetHeadModel; external atmcdDLL name 'GetHeadModel';
	  function atmcdGetHorizontalSpeed; external atmcdDLL name 'GetHorizontalSpeed';
	  function atmcdGetHSSpeed; external atmcdDLL name 'GetHSSpeed';
	  function atmcdGetHVflag; external atmcdDLL name 'GetHVflag';
	  function atmcdGetID; external atmcdDLL name 'GetID';
	  function atmcdGetImageFlip; external atmcdDLL name 'GetImageFlip';
	  function atmcdGetImageRotate; external atmcdDLL name 'GetImageRotate';
	  function atmcdGetImages; external atmcdDLL name 'GetImages';
	  function atmcdGetImages16; external atmcdDLL name 'GetImages16';
	  function atmcdGetImagesPerDMA; external atmcdDLL name 'GetImagesPerDMA';
	  function atmcdGetIRQ; external atmcdDLL name 'GetIRQ';
	  function atmcdGetKeepCleanTime; external atmcdDLL name 'GetKeepCleanTime';
	  function atmcdGetMaximumBinning; external atmcdDLL name 'GetMaximumBinning';
	  function atmcdGetMaximumExposure; external atmcdDLL name 'GetMaximumExposure';
	  function atmcdGetMaximumNumberRingExposureTimes; external atmcdDLL name 'GetMaximumNumberRingExposureTimes';
	  function atmcdGetMCPGain; external atmcdDLL name 'GetMCPGain';
	  function atmcdGetMCPGainRange; external atmcdDLL name 'GetMCPGainRange';
	  function atmcdGetMCPGainTable; external atmcdDLL name 'GetMCPGainTable';
	  function atmcdGetMCPVoltage; external atmcdDLL name 'GetMCPVoltage';
	  function atmcdGetMinimumImageLength; external atmcdDLL name 'GetMinimumImageLength';
	  function atmcdGetMinimumNumberInSeries; external atmcdDLL name 'GetMinimumNumberInSeries';
	  function atmcdGetMostRecentColorImage16; external atmcdDLL name 'GetMostRecentColorImage16';
	  function atmcdGetMostRecentImage; external atmcdDLL name 'GetMostRecentImage';
	  function atmcdGetMostRecentImage16; external atmcdDLL name 'GetMostRecentImage16';
	  function atmcdGetMSTimingsData; external atmcdDLL name 'GetMSTimingsData';
	  function atmcdGetMetaDataInfo; external atmcdDLL name 'GetMetaDataInfo';
	  function atmcdGetMSTimingsEnabled; external atmcdDLL name 'GetMSTimingsEnabled';
	  function atmcdGetRelativeImageTimes; external atmcdDLL name 'GetRelativeImageTimes';
	  function atmcdGetNewData; external atmcdDLL name 'GetNewData';
	  function atmcdGetNewData16; external atmcdDLL name 'GetNewData16';
	  function atmcdGetNewData8; external atmcdDLL name 'GetNewData8';
	  function atmcdGetNewFloatData; external atmcdDLL name 'GetNewFloatData';
	  function atmcdGetNumberADChannels; external atmcdDLL name 'GetNumberADChannels';
	  function atmcdGetNumberAmp; external atmcdDLL name 'GetNumberAmp';
	  function atmcdGetNumberAvailableImages; external atmcdDLL name 'GetNumberAvailableImages';
	  function atmcdGetNumberDDGExternalOutputs; external atmcdDLL name 'GetNumberDDGExternalOutputs';
	  function atmcdGetNumberDevices; external atmcdDLL name 'GetNumberDevices';
	  function atmcdGetNumberFKVShiftSpeeds; external atmcdDLL name 'GetNumberFKVShiftSpeeds';
	  function atmcdGetNumberHorizontalSpeeds; external atmcdDLL name 'GetNumberHorizontalSpeeds';
	  function atmcdGetNumberHSSpeeds; external atmcdDLL name 'GetNumberHSSpeeds';
	  function atmcdGetNumberNewImages; external atmcdDLL name 'GetNumberNewImages';
	  function atmcdGetNumberPhotonCountingDivisions; external atmcdDLL name 'GetNumberPhotonCountingDivisions';
	  function atmcdGetNumberPreAmpGains; external atmcdDLL name 'GetNumberPreAmpGains';
	  function atmcdGetNumberRingExposureTimes; external atmcdDLL name 'GetNumberRingExposureTimes';
	  function atmcdGetNumberIO; external atmcdDLL name 'GetNumberIO';
	  function atmcdGetNumberVerticalSpeeds; external atmcdDLL name 'GetNumberVerticalSpeeds';
	  function atmcdGetNumberVSAmplitudes; external atmcdDLL name 'GetNumberVSAmplitudes';
	  function atmcdGetNumberVSSpeeds; external atmcdDLL name 'GetNumberVSSpeeds';
	  function atmcdGetOldestImage; external atmcdDLL name 'GetOldestImage';
	  function atmcdGetOldestImage16; external atmcdDLL name 'GetOldestImage16';
	  function atmcdGetPhosphorStatus; external atmcdDLL name 'GetPhosphorStatus';
	  function atmcdGetPhysicalDMAAddress; external atmcdDLL name 'GetPhysicalDMAAddress';
	  function atmcdGetPixelSize; external atmcdDLL name 'GetPixelSize';
	  function atmcdGetPreAmpGain; external atmcdDLL name 'GetPreAmpGain';
	  function atmcdGetPreAmpGainText; external atmcdDLL name 'GetPreAmpGainText';
	  function atmcdGetDualExposureTimes; external atmcdDLL name 'GetDualExposureTimes';
	  function atmcdGetQE; external atmcdDLL name 'GetQE';
	  function atmcdGetReadOutTime; external atmcdDLL name 'GetReadOutTime';
	  function atmcdGetRegisterDump; external atmcdDLL name 'GetRegisterDump';
	  function atmcdGetRingExposureRange; external atmcdDLL name 'GetRingExposureRange';
	  function atmcdGetSDK3Handle; external atmcdDLL name 'GetSDK3Handle';
	  function atmcdGetSensitivity; external atmcdDLL name 'GetSensitivity';
	  function atmcdGetShutterMinTimes; external atmcdDLL name 'GetShutterMinTimes';
	  function atmcdGetSizeOfCircularBuffer; external atmcdDLL name 'GetSizeOfCircularBuffer';
	  function atmcdGetSlotBusDeviceFunction; external atmcdDLL name 'GetSlotBusDeviceFunction';
	  function atmcdGetSoftwareVersion; external atmcdDLL name 'GetSoftwareVersion';
	  function atmcdGetSpoolProgress; external atmcdDLL name 'GetSpoolProgress';
	  function atmcdGetStartUpTime; external atmcdDLL name 'GetStartUpTime';
	  function atmcdGetStatus; external atmcdDLL name 'GetStatus';
	  function atmcdGetTECStatus; external atmcdDLL name 'GetTECStatus';
	  function atmcdGetTemperature; external atmcdDLL name 'GetTemperature';
	  function atmcdGetTemperatureF; external atmcdDLL name 'GetTemperatureF';
	  function atmcdGetTemperatureRange; external atmcdDLL name 'GetTemperatureRange';
	  function atmcdGetTemperatureStatus; external atmcdDLL name 'GetTemperatureStatus';
	  function atmcdGetTotalNumberImagesAcquired; external atmcdDLL name 'GetTotalNumberImagesAcquired';
	  function atmcdGetIODirection; external atmcdDLL name 'GetIODirection';
	  function atmcdGetIOLevel; external atmcdDLL name 'GetIOLevel';
	  function atmcdGetVersionInfo; external atmcdDLL name 'GetVersionInfo';
	  function atmcdGetVerticalSpeed; external atmcdDLL name 'GetVerticalSpeed';
	  function atmcdGetVirtualDMAAddress; external atmcdDLL name 'GetVirtualDMAAddress';
	  function atmcdGetVSAmplitudeString; external atmcdDLL name 'GetVSAmplitudeString';
	  function atmcdGetVSAmplitudeFromString; external atmcdDLL name 'GetVSAmplitudeFromString';
	  function atmcdGetVSAmplitudeValue; external atmcdDLL name 'GetVSAmplitudeValue';
	  function atmcdGetVSSpeed; external atmcdDLL name 'GetVSSpeed';
	  function atmcdGPIBReceive; external atmcdDLL name 'GPIBReceive';
	  function atmcdGPIBSend; external atmcdDLL name 'GPIBSend';
	  function atmcdI2CBurstRead; external atmcdDLL name 'I2CBurstRead';
	  function atmcdI2CBurstWrite; external atmcdDLL name 'I2CBurstWrite';
	  function atmcdI2CRead; external atmcdDLL name 'I2CRead';
	  function atmcdI2CReset; external atmcdDLL name 'I2CReset';
	  function atmcdI2CWrite; external atmcdDLL name 'I2CWrite';
	  function atmcdIdAndorDll; external atmcdDLL name 'IdAndorDll';
	  function atmcdInAuxPort; external atmcdDLL name 'InAuxPort';
	  function atmcdInitialize; external atmcdDLL name 'Initialize';
	  function atmcdInitializeDevice; external atmcdDLL name 'InitializeDevice';
	  function atmcdIsAmplifierAvailable; external atmcdDLL name 'IsAmplifierAvailable';
	  function atmcdIsCoolerOn; external atmcdDLL name 'IsCoolerOn';
	  function atmcdIsCountConvertModeAvailable; external atmcdDLL name 'IsCountConvertModeAvailable';
	  function atmcdIsInternalMechanicalShutter; external atmcdDLL name 'IsInternalMechanicalShutter';
	  function atmcdIsPreAmpGainAvailable; external atmcdDLL name 'IsPreAmpGainAvailable';
	  function atmcdIsTriggerModeAvailable; external atmcdDLL name 'IsTriggerModeAvailable';
	  function atmcdMerge; external atmcdDLL name 'Merge';
	  function atmcdOutAuxPort; external atmcdDLL name 'OutAuxPort';
	  function atmcdPrepareAcquisition; external atmcdDLL name 'PrepareAcquisition';
	  function atmcdSaveAsBmp; external atmcdDLL name 'SaveAsBmp';
	  function atmcdSaveAsCommentedSif; external atmcdDLL name 'SaveAsCommentedSif';
	  function atmcdSaveAsEDF; external atmcdDLL name 'SaveAsEDF';
	  function atmcdSaveAsFITS; external atmcdDLL name 'SaveAsFITS';
	  function atmcdSaveAsRaw; external atmcdDLL name 'SaveAsRaw';
	  function atmcdSaveAsSif; external atmcdDLL name 'SaveAsSif';
	  function atmcdSaveAsSPC; external atmcdDLL name 'SaveAsSPC';
	  function atmcdSaveAsTiff; external atmcdDLL name 'SaveAsTiff';
	  function atmcdSaveAsTiffEx; external atmcdDLL name 'SaveAsTiffEx';
	  function atmcdSaveEEPROMToFile; external atmcdDLL name 'SaveEEPROMToFile';
	  function atmcdSaveToClipBoard; external atmcdDLL name 'SaveToClipBoard';
	  function atmcdSelectDevice; external atmcdDLL name 'SelectDevice';
	  function atmcdSendSoftwareTrigger; external atmcdDLL name 'SendSoftwareTrigger';
	  function atmcdSetAccumulationCycleTime; external atmcdDLL name 'SetAccumulationCycleTime';
	  function atmcdSetAcqStatusEvent; external atmcdDLL name 'SetAcqStatusEvent';
	  function atmcdSetAcquisitionMode; external atmcdDLL name 'SetAcquisitionMode';
	  function atmcdSetAcquisitionType; external atmcdDLL name 'SetAcquisitionType';
	  function atmcdSetADChannel; external atmcdDLL name 'SetADChannel';
	  function atmcdSetAdvancedTriggerModeState; external atmcdDLL name 'SetAdvancedTriggerModeState';
	  function atmcdSetBackground; external atmcdDLL name 'SetBackground';
	  function atmcdSetBaselineClamp; external atmcdDLL name 'SetBaselineClamp';
	  function atmcdSetBaselineOffset; external atmcdDLL name 'SetBaselineOffset';
	  function atmcdSetCameraLinkMode; external atmcdDLL name 'SetCameraLinkMode';
	  function atmcdSetCameraStatusEnable; external atmcdDLL name 'SetCameraStatusEnable';
	  function atmcdSetChargeShifting; external atmcdDLL name 'SetChargeShifting';
	  function atmcdSetComplexImage; external atmcdDLL name 'SetComplexImage';
	  function atmcdSetCoolerMode; external atmcdDLL name 'SetCoolerMode';
	  function atmcdSetCountConvertMode; external atmcdDLL name 'SetCountConvertMode';
	  function atmcdSetCountConvertWavelength; external atmcdDLL name 'SetCountConvertWavelength';
	  function atmcdSetCropMode; external atmcdDLL name 'SetCropMode';
	  function atmcdSetCurrentCamera; external atmcdDLL name 'SetCurrentCamera';
	  function atmcdSetCustomTrackHBin; external atmcdDLL name 'SetCustomTrackHBin';
	  function atmcdSetDataType; external atmcdDLL name 'SetDataType';
	  function atmcdSetDACOutput; external atmcdDLL name 'SetDACOutput';
	  function atmcdSetDACOutputScale; external atmcdDLL name 'SetDACOutputScale';
	  function atmcdSetDDGAddress; external atmcdDLL name 'SetDDGAddress';
	  function atmcdSetDDGExternalOutputEnabled; external atmcdDLL name 'SetDDGExternalOutputEnabled';
	  function atmcdSetDDGExternalOutputPolarity; external atmcdDLL name 'SetDDGExternalOutputPolarity';
	  function atmcdSetDDGExternalOutputStepEnabled; external atmcdDLL name 'SetDDGExternalOutputStepEnabled';
	  function atmcdSetDDGExternalOutputTime; external atmcdDLL name 'SetDDGExternalOutputTime';
	  function atmcdSetDDGGain; external atmcdDLL name 'SetDDGGain';
	  function atmcdSetDDGGateStep; external atmcdDLL name 'SetDDGGateStep';
	  function atmcdSetDDGGateTime; external atmcdDLL name 'SetDDGGateTime';
	  function atmcdSetDDGInsertionDelay; external atmcdDLL name 'SetDDGInsertionDelay';
	  function atmcdSetDDGIntelligate; external atmcdDLL name 'SetDDGIntelligate';
	  function atmcdSetDDGIOC; external atmcdDLL name 'SetDDGIOC';
	  function atmcdSetDDGIOCFrequency; external atmcdDLL name 'SetDDGIOCFrequency';
	  function atmcdSetDDGIOCNumber; external atmcdDLL name 'SetDDGIOCNumber';
	  function atmcdSetDDGIOCPeriod; external atmcdDLL name 'SetDDGIOCPeriod';
	  function atmcdSetDDGIOCTrigger; external atmcdDLL name 'SetDDGIOCTrigger';
	  function atmcdSetDDGOpticalWidthEnabled; external atmcdDLL name 'SetDDGOpticalWidthEnabled';
	  function atmcdSetDDGLiteGlobalControlByte; external atmcdDLL name 'SetDDGLiteGlobalControlByte';
	  function atmcdSetDDGLiteControlByte; external atmcdDLL name 'SetDDGLiteControlByte';
	  function atmcdSetDDGLiteInitialDelay; external atmcdDLL name 'SetDDGLiteInitialDelay';
	  function atmcdSetDDGLitePulseWidth; external atmcdDLL name 'SetDDGLitePulseWidth';
	  function atmcdSetDDGLiteInterPulseDelay; external atmcdDLL name 'SetDDGLiteInterPulseDelay';
	  function atmcdSetDDGLitePulsesPerExposure; external atmcdDLL name 'SetDDGLitePulsesPerExposure';
	  function atmcdSetDDGStepCoefficients; external atmcdDLL name 'SetDDGStepCoefficients';
	  function atmcdSetDDGWidthStepCoefficients; external atmcdDLL name 'SetDDGWidthStepCoefficients';
	  function atmcdSetDDGStepMode; external atmcdDLL name 'SetDDGStepMode';
	  function atmcdSetDDGWidthStepMode; external atmcdDLL name 'SetDDGWidthStepMode';
	  function atmcdSetDDGTimes; external atmcdDLL name 'SetDDGTimes';
	  function atmcdSetDDGTriggerMode; external atmcdDLL name 'SetDDGTriggerMode';
	  function atmcdSetDDGVariableGateStep; external atmcdDLL name 'SetDDGVariableGateStep';
	  function atmcdSetDelayGenerator; external atmcdDLL name 'SetDelayGenerator';
	  function atmcdSetDMAParameters; external atmcdDLL name 'SetDMAParameters';
	  function atmcdSetDriverEvent; external atmcdDLL name 'SetDriverEvent';
	  function atmcdSetEMAdvanced; external atmcdDLL name 'SetEMAdvanced';
	  function atmcdSetEMCCDGain; external atmcdDLL name 'SetEMCCDGain';
	  function atmcdSetEMClockCompensation; external atmcdDLL name 'SetEMClockCompensation';
	  function atmcdSetEMGainMode; external atmcdDLL name 'SetEMGainMode';
	  function atmcdSetExposureTime; external atmcdDLL name 'SetExposureTime';
	  function atmcdSetExternalTriggerTermination; external atmcdDLL name 'SetExternalTriggerTermination';
	  function atmcdSetFanMode; external atmcdDLL name 'SetFanMode';
	  function atmcdSetFastExtTrigger; external atmcdDLL name 'SetFastExtTrigger';
	  function atmcdSetFastKinetics; external atmcdDLL name 'SetFastKinetics';
	  function atmcdSetFastKineticsEx; external atmcdDLL name 'SetFastKineticsEx';
	  function atmcdSetFilterMode; external atmcdDLL name 'SetFilterMode';
	  function atmcdSetFilterParameters; external atmcdDLL name 'SetFilterParameters';
	  function atmcdSetFKVShiftSpeed; external atmcdDLL name 'SetFKVShiftSpeed';
	  function atmcdSetFPDP; external atmcdDLL name 'SetFPDP';
	  function atmcdSetFrameTransferMode; external atmcdDLL name 'SetFrameTransferMode';
	  function atmcdSetFrontEndEvent; external atmcdDLL name 'SetFrontEndEvent';
	  function atmcdSetFullImage; external atmcdDLL name 'SetFullImage';
	  function atmcdSetFVBHBin; external atmcdDLL name 'SetFVBHBin';
	  function atmcdSetGain; external atmcdDLL name 'SetGain';
	  function atmcdSetGate; external atmcdDLL name 'SetGate';
	  function atmcdSetGateMode; external atmcdDLL name 'SetGateMode';
	  function atmcdSetHighCapacity; external atmcdDLL name 'SetHighCapacity';
	  function atmcdSetHorizontalSpeed; external atmcdDLL name 'SetHorizontalSpeed';
	  function atmcdSetHSSpeed; external atmcdDLL name 'SetHSSpeed';
	  function atmcdSetImage; external atmcdDLL name 'SetImage';
	  function atmcdSetImageFlip; external atmcdDLL name 'SetImageFlip';
	  function atmcdSetImageRotate; external atmcdDLL name 'SetImageRotate';
	  function atmcdSetIsolatedCropMode; external atmcdDLL name 'SetIsolatedCropMode';
	  function atmcdSetIsolatedCropModeEx; external atmcdDLL name 'SetIsolatedCropModeEx';
	  function atmcdSetKineticCycleTime; external atmcdDLL name 'SetKineticCycleTime';
	  function atmcdSetMCPGain; external atmcdDLL name 'SetMCPGain';
	  function atmcdSetMCPGating; external atmcdDLL name 'SetMCPGating';
	  function atmcdSetMessageWindow; external atmcdDLL name 'SetMessageWindow';
	  function atmcdSetMetaData; external atmcdDLL name 'SetMetaData';
	  function atmcdSetMultiTrack; external atmcdDLL name 'SetMultiTrack';
	  function atmcdSetMultiTrackHBin; external atmcdDLL name 'SetMultiTrackHBin';
	  function atmcdSetMultiTrackHRange; external atmcdDLL name 'SetMultiTrackHRange';
	  function atmcdSetMultiTrackScan; external atmcdDLL name 'SetMultiTrackScan';
	  function atmcdSetNextAddress; external atmcdDLL name 'SetNextAddress';
	  function atmcdSetNextAddress16; external atmcdDLL name 'SetNextAddress16';
	  function atmcdSetNumberAccumulations; external atmcdDLL name 'SetNumberAccumulations';
	  function atmcdSetNumberKinetics; external atmcdDLL name 'SetNumberKinetics';
	  function atmcdSetNumberPrescans; external atmcdDLL name 'SetNumberPrescans';
	  function atmcdSetOutputAmplifier; external atmcdDLL name 'SetOutputAmplifier';
	  function atmcdSetOverlapMode; external atmcdDLL name 'SetOverlapMode';
	  function atmcdSetPCIMode; external atmcdDLL name 'SetPCIMode';
	  function atmcdSetPhotonCounting; external atmcdDLL name 'SetPhotonCounting';
	  function atmcdSetPhotonCountingThreshold; external atmcdDLL name 'SetPhotonCountingThreshold';
	  function atmcdSetPhosphorEvent; external atmcdDLL name 'SetPhosphorEvent';
	  function atmcdSetPhotonCountingDivisions; external atmcdDLL name 'SetPhotonCountingDivisions';
	  function atmcdSetPixelMode; external atmcdDLL name 'SetPixelMode';
	  function atmcdSetPreAmpGain; external atmcdDLL name 'SetPreAmpGain';
	  function atmcdSetDualExposureTimes; external atmcdDLL name 'SetDualExposureTimes';
	  function atmcdSetDualExposureMode; external atmcdDLL name 'SetDualExposureMode';
	  function atmcdSetRandomTracks; external atmcdDLL name 'SetRandomTracks';
	  function atmcdSetReadMode; external atmcdDLL name 'SetReadMode';
	  function atmcdSetReadoutRegisterPacking; external atmcdDLL name 'SetReadoutRegisterPacking';
	  function atmcdSetRegisterDump; external atmcdDLL name 'SetRegisterDump';
	  function atmcdSetRingExposureTimes; external atmcdDLL name 'SetRingExposureTimes';
	  function atmcdSetSaturationEvent; external atmcdDLL name 'SetSaturationEvent';
	  function atmcdSetShutter; external atmcdDLL name 'SetShutter';
	  function atmcdSetShutterEx; external atmcdDLL name 'SetShutterEx';
	  function atmcdSetShutters; external atmcdDLL name 'SetShutters';
	  function atmcdSetSifComment; external atmcdDLL name 'SetSifComment';
	  function atmcdSetSingleTrack; external atmcdDLL name 'SetSingleTrack';
	  function atmcdSetSingleTrackHBin; external atmcdDLL name 'SetSingleTrackHBin';
	  function atmcdSetSpool; external atmcdDLL name 'SetSpool';
	  function atmcdSetSpoolThreadCount; external atmcdDLL name 'SetSpoolThreadCount';
	  function atmcdSetStorageMode; external atmcdDLL name 'SetStorageMode';
	  function atmcdSetTECEvent; external atmcdDLL name 'SetTECEvent';
	  function atmcdSetTemperature; external atmcdDLL name 'SetTemperature';
	  function atmcdSetTemperatureEvent; external atmcdDLL name 'SetTemperatureEvent';
	  function atmcdSetTriggerMode; external atmcdDLL name 'SetTriggerMode';
	  function atmcdSetTriggerInvert; external atmcdDLL name 'SetTriggerInvert';
	  function atmcdGetTriggerLevelRange; external atmcdDLL name 'GetTriggerLevelRange';
	  function atmcdSetTriggerLevel; external atmcdDLL name 'SetTriggerLevel';
	  function atmcdSetIODirection; external atmcdDLL name 'SetIODirection';
	  function atmcdSetIOLevel; external atmcdDLL name 'SetIOLevel';
	  function atmcdSetUserEvent; external atmcdDLL name 'SetUserEvent';
	  function atmcdSetUSGenomics; external atmcdDLL name 'SetUSGenomics';
	  function atmcdSetVerticalRowBuffer; external atmcdDLL name 'SetVerticalRowBuffer';
	  function atmcdSetVerticalSpeed; external atmcdDLL name 'SetVerticalSpeed';
	  function atmcdSetVirtualChip; external atmcdDLL name 'SetVirtualChip';
	  function atmcdSetVSAmplitude; external atmcdDLL name 'SetVSAmplitude';
	  function atmcdSetVSSpeed; external atmcdDLL name 'SetVSSpeed';
	  function atmcdShutDown; external atmcdDLL name 'ShutDown';
	  function atmcdStartAcquisition; external atmcdDLL name 'StartAcquisition';
	  function atmcdUnMapPhysicalAddress; external atmcdDLL name 'UnMapPhysicalAddress';
	  function atmcdWaitForAcquisition; external atmcdDLL name 'WaitForAcquisition';
	  function atmcdWaitForAcquisitionByHandle; external atmcdDLL name 'WaitForAcquisitionByHandle';
	  function atmcdWaitForAcquisitionByHandleTimeOut; external atmcdDLL name 'WaitForAcquisitionByHandleTimeOut';
	  function atmcdWaitForAcquisitionTimeOut; external atmcdDLL name 'WaitForAcquisitionTimeOut';
	  function atmcdWhiteBalance; external atmcdDLL name 'WhiteBalance';
	  function atmcdOA_Initialize; external atmcdDLL name 'OA_Initialize';
	  function atmcdOA_EnableMode; external atmcdDLL name 'OA_EnableMode';
	  function atmcdOA_GetModeAcqParams; external atmcdDLL name 'OA_GetModeAcqParams';
	  function atmcdOA_GetUserModeNames; external atmcdDLL name 'OA_GetUserModeNames';
	  function atmcdOA_GetPreSetModeNames; external atmcdDLL name 'OA_GetPreSetModeNames';
	  function atmcdOA_GetNumberOfUserModes; external atmcdDLL name 'OA_GetNumberOfUserModes';
	  function atmcdOA_GetNumberOfPreSetModes; external atmcdDLL name 'OA_GetNumberOfPreSetModes';
	  function atmcdOA_GetNumberOfAcqParams; external atmcdDLL name 'OA_GetNumberOfAcqParams';
	  function atmcdOA_AddMode; external atmcdDLL name 'OA_AddMode';
	  function atmcdOA_WriteToFile; external atmcdDLL name 'OA_WriteToFile';
	  function atmcdOA_DeleteMode; external atmcdDLL name 'OA_DeleteMode';
	  function atmcdOA_SetInt; external atmcdDLL name 'OA_SetInt';
	  function atmcdOA_SetFloat; external atmcdDLL name 'OA_SetFloat';
	  function atmcdOA_SetString; external atmcdDLL name 'OA_SetString';
	  function atmcdOA_GetInt; external atmcdDLL name 'OA_GetInt';
	  function atmcdOA_GetFloat; external atmcdDLL name 'OA_GetFloat';
	  function atmcdOA_GetString; external atmcdDLL name 'OA_GetString';
	  function atmcdFilter_SetMode; external atmcdDLL name 'Filter_SetMode';
	  function atmcdFilter_GetMode; external atmcdDLL name 'Filter_GetMode';
	  function atmcdFilter_SetThreshold; external atmcdDLL name 'Filter_SetThreshold';
	  function atmcdFilter_GetThreshold; external atmcdDLL name 'Filter_GetThreshold';
	  function atmcdFilter_SetDataAveragingMode; external atmcdDLL name 'Filter_SetDataAveragingMode';
	  function atmcdFilter_GetDataAveragingMode; external atmcdDLL name 'Filter_GetDataAveragingMode';
	  function atmcdFilter_SetAveragingFrameCount; external atmcdDLL name 'Filter_SetAveragingFrameCount';
	  function atmcdFilter_GetAveragingFrameCount; external atmcdDLL name 'Filter_GetAveragingFrameCount';
	  function atmcdFilter_SetAveragingFactor; external atmcdDLL name 'Filter_SetAveragingFactor';
	  function atmcdFilter_GetAveragingFactor; external atmcdDLL name 'Filter_GetAveragingFactor';
	  function atmcdPostProcessNoiseFilter; external atmcdDLL name 'PostProcessNoiseFilter';
	  function atmcdPostProcessCountConvert; external atmcdDLL name 'PostProcessCountConvert';
	  function atmcdPostProcessPhotonCounting; external atmcdDLL name 'PostProcessPhotonCounting';
	  function atmcdPostProcessDataAveraging; external atmcdDLL name 'PostProcessDataAveraging';

end.
